"""initial_schema

Revision ID: 093a1c363916
Revises: 
Create Date: 2026-09-09 18:27:14.669693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093a1c363916'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ANALISIS_FINANCIERO', 'Ganancia',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('CAJA', 'Monto_Base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('CAJA', 'Monto_Efectivo',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=True)
    op.alter_column('CAJA', 'Monto_Transaccion',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=True)
    op.alter_column('CAJA', 'Monto_Final_calculado',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=True)
    op.alter_column('CAJA', 'ID_Usuario',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('DETALLE_FACTURAS', 'Precio_unitario',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('DETALLE_FACTURAS', 'Subtotal',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('EGRESOS', 'Monto_Egreso',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('FACTURA', 'Monto_efectivo',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('FACTURA', 'Monto_TRANSACCION',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('FACTURA', 'Descuento',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Precio_costo',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Precio_venta_1',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Precio_venta_2',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Precio_venta_3',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Precio_venta_4',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Ganancia_1',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Ganancia_2',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Ganancia_3',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Ganancia_4',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('PAGO_CREDITO', 'Monto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Precio_costo',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Precio_venta_1',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Precio_venta_2',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Precio_venta_3',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Precio_venta_4',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Ganancia_1',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Ganancia_2',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Ganancia_3',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Ganancia_4',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('VENTA_CREDITO', 'Total_Deuda',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('VENTA_CREDITO', 'Saldo_Pendiente',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('VENTA_CREDITO', 'Saldo_Pendiente',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('VENTA_CREDITO', 'Total_Deuda',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Ganancia_4',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Ganancia_3',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Ganancia_2',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Ganancia_1',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Precio_venta_4',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Precio_venta_3',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Precio_venta_2',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Precio_venta_1',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('PRODUCTOS', 'Precio_costo',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('PAGO_CREDITO', 'Monto',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Ganancia_4',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Ganancia_3',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Ganancia_2',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Ganancia_1',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Precio_venta_4',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Precio_venta_3',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Precio_venta_2',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Precio_venta_1',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('LOTES_PRODUCTO', 'Precio_costo',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('FACTURA', 'Descuento',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('FACTURA', 'Monto_TRANSACCION',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('FACTURA', 'Monto_efectivo',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('EGRESOS', 'Monto_Egreso',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('DETALLE_FACTURAS', 'Subtotal',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('DETALLE_FACTURAS', 'Precio_unitario',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('CAJA', 'ID_Usuario',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('CAJA', 'Monto_Final_calculado',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('CAJA', 'Monto_Transaccion',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('CAJA', 'Monto_Efectivo',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('CAJA', 'Monto_Base',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('ANALISIS_FINANCIERO', 'Ganancia',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
