# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ControlUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ControlUsuario(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1385, 1035)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);\n" "")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Contenedor = QtWidgets.QWidget(Form)
        self.Contenedor.setStyleSheet(
            "\n"
            "QPushButton {\n"
            "    background-color: black; /* Fondo blanco */\n"
            "    border: none; /* Sin borde ni decoración inicial */\n"
            "    color:  white; /* Color del texto */\n"
            "    border-radius: 15px; /* Bordes circulares */\n"
            "    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
            "    height: 40px; /* Altura del botón */\n"
            "    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
            "    font-size: 18px; /* Tamaño de fuente */\n"
            "    margin-top:20px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
            "    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
            "}\n"
            "\n"
            "QToolButton {\n"
            "    background-color: white; /* Fondo blanco */\n"
            "    border: none; /* Sin borde ni decoración inicial */\n"
            "    color:  rgb(50, 50, 50); /* Color del texto */\n"
            "    border-radius: 15px; /* Bordes circulares */\n"
            "    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
            "    height: 40px; /* Altura del botón */\n"
            "    text-align: left; /* Alinea el texto del botón a la izquierda */\n"
            "    font-size: 18px; /* Tamaño de fuente */\n"
            "    cursor: pointer;\n"
            "}\n"
            "\n"
            "QToolButton:hover {\n"
            "    background-color: #f2f2f2; /* Gris claro al pasar el mouse */\n"
            "    cursor: pointer;\n"
            "}\n"
            "QLineEdit {\n"
            "    background-color: rgb(255, 255, 255); /* Fondo blanco */\n"
            "    border: none; /* Sin bordes visibles */\n"
            "    padding: 4px; /* Espaciado interno entre el texto y los bordes */\n"
            "    margin-right: 5px; /* Espaciado externo solo a la derecha */\n"
            "    border-radius: 10px; /* Bordes redondeados */\n"
            "    color: black; /* Texto negro */\n"
            "    text-align: left; /* Texto alineado a la izquierda */\n"
            "    font-size: 18px; /* Tamaño del texto */\n"
            "}\n"
            "\n"
            "/* Cuando el QLineEdit está enfocado (se está escribiendo) */\n"
            "QLineEdit:focus {\n"
            "    background-color: rgb(230, 230, 250); /* Color de fondo cuando el campo está activo */\n"
            "    border: 1px solid rgb(0, 0, 0); /* Borde negro al estar activo */\n"
            "}\n"
            "\n"
            "QLabel {\n"
            "    font-size: 20px; /* Tamaño de fuente */\n"
            "    color:  black; /* Color del texto */\n"
            "    margin-right: 10px; /* Espaciado a la derecha */\n"
            "    padding: 5px; /* Espaciado interno */\n"
            "    text-align: left; /* Alineación del texto a la izquierda */\n"
            "}\n"
            "QTableWidget {\n"
            "    border: none;\n"
            "    background-color: #ffffff; /* Fondo blanco para la tabla */\n"
            "    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Sombra suave alrededor de la tabla */\n"
            "}\n"
            "\n"
            "QTableWidget::item {\n"
            "    background-color: #f2f2f2; \n"
            "    border: none; \n"
            "    transition: background-color 0.3s ease; /* Suavizado de transición de color de fondo */\n"
            "    pointer-events: none; /* Desactiva la interacción con las celdas (como editar) */\n"
            "}\n"
            "\n"
            "QTableWidget::item:selected {\n"
            "    background-color: #aad4ff; /* Color azul claro para celdas seleccionadas */\n"
            "    color: black; /* Texto negro para celdas seleccionadas */\n"
            "}\n"
            "\n"
            "QTableWidget::item:hover {\n"
            "    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
            "}\n"
            "\n"
            "QHeaderView::section {\n"
            "    border: none; \n"
            "    background-color: #f2f2f2; \n"
            "    font-weight: normal; /* No negritas */\n"
            "    text-align: center; /* Centrado del texto en los encabezados */\n"
            "    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Sombra suave para los encabezados */\n"
            "}\n"
            "\n"
            "QHeaderView::section:focus {\n"
            "    background-color: #f2f2f2; /* Sin color de fondo cuando está en foco */\n"
            "    border: none; /* Sin borde cuando está en foco */\n"
            "}\n"
            "\n"
            "QTableWidget::item:focus {\n"
            "    border: none; /* Sin borde cuando las celdas tienen el foco */\n"
            "    background-color: #f2f2f2; /* Mantener el fondo sin color azul */\n"
            "}\n"
            "\n"
            "QTableCornerButton::section {\n"
            "    background-color: #f2f2f2; \n"
            "    border: none; \n"
            "}\n"
            "\n"
            "QTableWidget::verticalHeader {\n"
            "    background-color: #f2f2f2;\n"
            "    border: none;\n"
            "    font-weight: normal; /* No negritas */\n"
            "}\n"
            "\n"
            "QTableWidget::item:hover {\n"
            "    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
            "}\n"
            "\n"
            "/* Personalización de la barra de desplazamiento */\n"
            "QScrollBar:vertical {\n"
            "    border: none;\n"
            "    background: #f7f7f7; /* Fondo de la barra */\n"
            "    width: 8px; /* Barra más delgada */\n"
            "    border-radius: 4px; /* Bordes más redondeados */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:vertical {\n"
            "    background: #bbb; /* Fondo del control deslizante */\n"
            "    min-height: 20px; /* Control deslizante más delgado */\n"
            "    border-radius: 4px; /* Bordes redondeados */\n"
            "    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:vertical:hover {\n"
            "    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
            "}\n"
            "\n"
            "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
            "    border: none;\n"
            "    background: #f2f2f2; /* Fondo para los botones de la barra */\n"
            "    height: 0px; /* Sin altura para los botones */\n"
            "}\n"
            "\n"
            "QScrollBar:horizontal {\n"
            "    border: none;\n"
            "    background: #f7f7f7; /* Fondo de la barra */\n"
            "    height: 8px; /* Barra más delgada */\n"
            "    border-radius: 4px; /* Bordes más redondeados */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:horizontal {\n"
            "    background: #bbb; /* Fondo del control deslizante */\n"
            "    min-width: 20px; /* Control deslizante más delgado */\n"
            "    border-radius: 4px; /* Bordes redondeados */\n"
            "    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:horizontal:hover {\n"
            "    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
            "}\n"
            "\n"
            "QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
            "    border: none;\n"
            "    background: #f2f2f2; /* Fondo para los botones de la barra */\n"
            "    width: 0px; /* Sin ancho para los botones */\n"
            "}\n"
            "\n"
            "\n"
            ""
        )
        self.Contenedor.setObjectName("Contenedor")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Contenedor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Contenido = QtWidgets.QStackedWidget(self.Contenedor)
        self.Contenido.setStyleSheet(
            "margin-left:10px;\n"
            "border-radius:15px;\n"
            "background-color: #f2f2f2; \n"
            ""
        )
        self.Contenido.setObjectName("Contenido")
        self.ContenidoPage1 = QtWidgets.QWidget()
        self.ContenidoPage1.setObjectName("ContenidoPage1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ContenidoPage1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.ContenidoPage1)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.InputNombreUser = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.InputNombreUser.sizePolicy().hasHeightForWidth()
        )
        self.InputNombreUser.setSizePolicy(sizePolicy)
        self.InputNombreUser.setMinimumSize(QtCore.QSize(250, 50))
        self.InputNombreUser.setMaximumSize(QtCore.QSize(250, 50))
        self.InputNombreUser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputNombreUser.setObjectName("InputNombreUser")
        self.gridLayout_2.addWidget(self.InputNombreUser, 3, 1, 1, 1)
        self.LabelVentasA = QtWidgets.QLabel(self.widget_3)
        self.LabelVentasA.setStyleSheet(
            "#LabelVentasA {\n"
            "    font-weight: bold; /* Negrita */\n"
            "    font-size: 34px; /* Tamaño de fuente */\n"
            "}\n"
            ""
        )
        self.LabelVentasA.setObjectName("LabelVentasA")
        self.gridLayout_2.addWidget(self.LabelVentasA, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget_3)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 2, 1, 1)
        self.InputPasswordUser = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.InputPasswordUser.sizePolicy().hasHeightForWidth()
        )
        self.InputPasswordUser.setSizePolicy(sizePolicy)
        self.InputPasswordUser.setMinimumSize(QtCore.QSize(250, 50))
        self.InputPasswordUser.setMaximumSize(QtCore.QSize(250, 50))
        self.InputPasswordUser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputPasswordUser.setObjectName("InputPasswordUser")
        self.gridLayout_2.addWidget(self.InputPasswordUser, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 3, 1, 1)
        self.InputIdUser = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputIdUser.sizePolicy().hasHeightForWidth())
        self.InputIdUser.setSizePolicy(sizePolicy)
        self.InputIdUser.setMinimumSize(QtCore.QSize(250, 50))
        self.InputIdUser.setMaximumSize(QtCore.QSize(250, 50))
        self.InputIdUser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputIdUser.setObjectName("InputIdUser")
        self.gridLayout_2.addWidget(self.InputIdUser, 3, 0, 1, 1)
        self.InputUser = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputUser.sizePolicy().hasHeightForWidth())
        self.InputUser.setSizePolicy(sizePolicy)
        self.InputUser.setMinimumSize(QtCore.QSize(250, 50))
        self.InputUser.setMaximumSize(QtCore.QSize(250, 50))
        self.InputUser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputUser.setObjectName("InputUser")
        self.gridLayout_2.addWidget(self.InputUser, 3, 2, 1, 1)
        self.BtnRolUser = QtWidgets.QPushButton(self.widget_3)
        self.BtnRolUser.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(0, 0, 0);"
        )
        self.BtnRolUser.setObjectName("BtnRolUser")
        self.gridLayout_2.addWidget(self.BtnRolUser, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.BtnRegistrarUser = QtWidgets.QPushButton(self.widget_3)
        self.BtnRegistrarUser.setStyleSheet(
            "\n"
            "QPushButton {\n"
            "    background-color: black; /* Fondo blanco */\n"
            "    border: none; /* Sin borde ni decoración inicial */\n"
            "    color:  white; /* Color del texto */\n"
            "    border-radius: 15px; /* Bordes circulares */\n"
            "    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
            "    height: 40px; /* Altura del botón */\n"
            "    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
            "    font-size: 18px; /* Tamaño de fuente */\n"
            "    margin-top:20px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
            "    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
            "}"
        )
        self.BtnRegistrarUser.setObjectName("BtnRegistrarUser")
        self.gridLayout_2.addWidget(self.BtnRegistrarUser, 5, 2, 1, 1)
        self.BtnEliminar = QtWidgets.QPushButton(self.widget_3)
        self.BtnEliminar.setStyleSheet(
            "\n"
            "QPushButton {\n"
            "    background-color: red; /* Fondo blanco */\n"
            "    border: none; /* Sin borde ni decoración inicial */\n"
            "    color:  white; /* Color del texto */\n"
            "    border-radius: 15px; /* Bordes circulares */\n"
            "    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
            "    height: 40px; /* Altura del botón */\n"
            "    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
            "    font-size: 18px; /* Tamaño de fuente */\n"
            "    margin-top:20px;\n"
            "    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
            "    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
            "}"
        )
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("assets/iconos/eliminar.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.BtnEliminar.setIcon(icon)
        self.BtnEliminar.setIconSize(QtCore.QSize(30, 30))
        self.BtnEliminar.setObjectName("BtnEliminar")
        self.gridLayout_2.addWidget(self.BtnEliminar, 5, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignHCenter)
        self.widget_2 = QtWidgets.QWidget(self.ContenidoPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(1200, 0))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setStyleSheet(
            "QLineEdit {\n"
            "    border: none;\n"
            "    border-bottom: 0.5px solid gray;\n"
            "}\n"
            "\n"
            "QLineEdit:focus {\n"
            "    border: none;\n"
            "    border-bottom: 1.5px solid black; /* Cambia el color y grosor según desees */\n"
            "}\n"
            ""
        )
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets/iconos/buscar.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignHCenter)
        self.widget = QtWidgets.QWidget(self.ContenidoPage1)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.TablaUser = QtWidgets.QTableWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TablaUser.sizePolicy().hasHeightForWidth())
        self.TablaUser.setSizePolicy(sizePolicy)
        self.TablaUser.setMinimumSize(QtCore.QSize(750, 500))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.TablaUser.setFont(font)
        self.TablaUser.setStyleSheet(
            "\n"
            "QTableWidget {\n"
            "    border: none;\n"
            "    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Sombra suave alrededor de la tabla */\n"
            "}\n"
            "\n"
            "QTableWidget::item {\n"
            "    background-color: #f2f2f2; \n"
            "    border: none; \n"
            "    font-size: 18px; /* Tamaño de letra */\n"
            "    transition: background-color 0.3s ease; /* Suavizado de transición de color de fondo */\n"
            "    pointer-events: none; /* Desactiva la interacción con las celdas (como editar) */\n"
            "}\n"
            "\n"
            "QTableWidget::item:selected {\n"
            "    background-color: #aad4ff; /* Color azul claro para celdas seleccionadas */\n"
            "    color: black; /* Texto negro para celdas seleccionadas */\n"
            "}\n"
            "\n"
            "QTableWidget::item:hover {\n"
            "    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
            "}\n"
            "\n"
            "QHeaderView::section {\n"
            "    border: none; \n"
            "    background-color: #f2f2f2; \n"
            "    font-size: 18px; /* Tamaño de letra */\n"
            "    font-weight: normal; /* No negritas */\n"
            "    text-align: center; /* Centrado del texto en los encabezados */\n"
            "    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Sombra suave para los encabezados */\n"
            "}\n"
            "\n"
            "QHeaderView::section:focus {\n"
            "    background-color: #f2f2f2; /* Sin color de fondo cuando está en foco */\n"
            "    border: none; /* Sin borde cuando está en foco */\n"
            "}\n"
            "\n"
            "QTableWidget::item:focus {\n"
            "    border: none; /* Sin borde cuando las celdas tienen el foco */\n"
            "    background-color: #f2f2f2; /* Mantener el fondo sin color azul */\n"
            "}\n"
            "\n"
            "QTableCornerButton::section {\n"
            "    background-color: #f2f2f2; \n"
            "    border: none; \n"
            "}\n"
            "\n"
            "QTableWidget::verticalHeader {\n"
            "    background-color: #f2f2f2;\n"
            "    font-size: 23px;\n"
            "    border: none;\n"
            "    font-weight: normal; /* No negritas */\n"
            "}\n"
            "\n"
            "QTableWidget::item:hover {\n"
            "    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
            "}\n"
            "/* Personalización de la barra de desplazamiento */\n"
            "QScrollBar:vertical {\n"
            "    border: none;\n"
            "    background: #f7f7f7; /* Fondo de la barra */\n"
            "    width: 8px; /* Barra más delgada */\n"
            "    border-radius: 4px; /* Bordes más redondeados */\n"
            "    margin: 0px 2px 0px 0px; /* Un pequeño margen para el desplazamiento */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:vertical {\n"
            "    background: #bbb; /* Fondo del control deslizante */\n"
            "    min-height: 20px; /* Control deslizante más delgado */\n"
            "    border-radius: 4px; /* Bordes redondeados */\n"
            "    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:vertical:hover {\n"
            "    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
            "}\n"
            "\n"
            "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
            "    border: none;\n"
            "    background: #f2f2f2; /* Fondo para los botones de la barra */\n"
            "    height: 0px; /* Sin altura para los botones */\n"
            "}\n"
            "\n"
            "QScrollBar:horizontal {\n"
            "    border: none;\n"
            "    background: #f7f7f7; /* Fondo de la barra */\n"
            "    height: 8px; /* Barra más delgada */\n"
            "    border-radius: 4px; /* Bordes más redondeados */\n"
            "    margin: 0px 0px 2px 0px; /* Un pequeño margen para el desplazamiento */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:horizontal {\n"
            "    background: #bbb; /* Fondo del control deslizante */\n"
            "    min-width: 20px; /* Control deslizante más delgado */\n"
            "    border-radius: 4px; /* Bordes redondeados */\n"
            "    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:horizontal:hover {\n"
            "    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
            "}\n"
            ""
        )
        self.TablaUser.setObjectName("TablaUser")
        self.TablaUser.setColumnCount(6)
        self.TablaUser.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaUser.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setKerning(False)
        item.setFont(font)
        self.TablaUser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaUser.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaUser.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaUser.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaUser.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaUser.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(
            self.TablaUser, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter
        )
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(self.ContenidoPage1)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2.addWidget(
            self.widget_4, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter
        )
        self.Contenido.addWidget(self.ContenidoPage1)
        self.horizontalLayout_2.addWidget(self.Contenido)
        self.horizontalLayout.addWidget(self.Contenedor)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LabelVentasA.setText(_translate("Form", "Usuarios"))
        self.label_7.setText(_translate("Form", "Usuario"))
        self.label_5.setText(_translate("Form", "Nombre"))
        self.label.setText(_translate("Form", "Contraseña"))
        self.BtnRolUser.setText(_translate("Form", "Asesor Comercial"))
        self.label_6.setText(_translate("Form", "Rol"))
        self.label_3.setText(_translate("Form", "ID"))
        self.BtnRegistrarUser.setText(_translate("Form", "Registrar Usuario"))
        self.BtnEliminar.setText(_translate("Form", "   Eliminar Usuario"))
        item = self.TablaUser.verticalHeaderItem(0)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(1)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(2)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(3)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(4)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(5)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(6)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(7)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(8)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(9)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(10)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(11)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(12)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(13)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaUser.verticalHeaderItem(14)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaUser.verticalHeaderItem(15)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaUser.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID "))
        item = self.TablaUser.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.TablaUser.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Usuario"))
        item = self.TablaUser.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Contraseña"))
        item = self.TablaUser.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Rol"))
        item = self.TablaUser.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Estado"))
